<?php

/**
 * This file is auto-generated. Do not edit manually.
 * Generated: 2026-06-10 02:24:37 UTC
 * Spec: https://raw.githubusercontent.com/cloudflare/api-schemas/main/openapi.json
 */

declare(strict_types=1);

namespace FoundryCo\Cloudflare\Responses;

readonly class DnssecDnssecDetails
{
	public function __construct(
		/** Algorithm key code. */
		public ?string $algorithm = null,
		/** Digest hash. */
		public ?string $digest = null,
		/** Type of digest algorithm. */
		public ?string $digestAlgorithm = null,
		/** Coded type for digest algorithm. */
		public ?string $digestType = null,
		/**
		 * If true, multi-signer DNSSEC is enabled on the zone, allowing multiple
		 * providers to serve a DNSSEC-signed zone at the same time.
		 * This is required for DNSKEY records (except those automatically
		 * generated by Cloudflare) to be added to the zone.
		 *
		 * See [Multi-signer DNSSEC](https://developers.cloudflare.com/dns/dnssec/multi-signer-dnssec/) for details.
		 */
		public ?bool $dnssecMultiSigner = null,
		/**
		 * If true, allows Cloudflare to transfer in a DNSSEC-signed zone
		 * including signatures from an external provider, without requiring
		 * Cloudflare to sign any records on the fly.
		 *
		 * Note that this feature has some limitations.
		 * See [Cloudflare as Secondary](https://developers.cloudflare.com/dns/zone-setups/zone-transfers/cloudflare-as-secondary/setup/#dnssec) for details.
		 */
		public ?bool $dnssecPresigned = null,
		/**
		 * If true, enables the use of NSEC3 together with DNSSEC on the zone.
		 * Combined with setting dnssec_presigned to true, this enables the use of
		 * NSEC3 records when transferring in from an external provider.
		 * If dnssec_presigned is instead set to false (default), NSEC3 records will be
		 * generated and signed at request time.
		 *
		 * See [DNSSEC with NSEC3](https://developers.cloudflare.com/dns/dnssec/enable-nsec3/) for details.
		 */
		public ?bool $dnssecUseNsec3 = null,
		/** Full DS record. */
		public ?string $ds = null,
		/** Flag for DNSSEC record. */
		public ?float $flags = null,
		/** Code for key tag. */
		public ?float $keyTag = null,
		/** Algorithm key type. */
		public ?string $keyType = null,
		/** When DNSSEC was last modified. */
		public ?\DateTimeImmutable $modifiedOn = null,
		/** Public key for DS record. */
		public ?string $publicKey = null,
		/** Status of DNSSEC, based on user-desired state and presence of necessary records. */
		public ?\FoundryCo\Cloudflare\Enums\DnssecDnssecDetailsStatus $status = null,
	) {
	}
}
