<?php

/**
 * This file is auto-generated. Do not edit manually.
 * Generated: 2026-06-09 21:41:47 UTC
 * Spec: https://raw.githubusercontent.com/cloudflare/api-schemas/main/openapi.json
 */

declare(strict_types=1);

namespace FoundryCo\Cloudflare\Responses;

readonly class IPAddressManagementPrefixesDocument
{
	public function __construct(
		/** Identifier of a Cloudflare account. */
		public ?string $accountId = null,
		/** Whether the LOA has been auto-generated for the prefix owner by Cloudflare. */
		public ?bool $autoGenerated = null,
		public ?\DateTimeImmutable $created = null,
		/** Name of LOA document. Max file size 10MB, and supported filetype is pdf. */
		public ?string $filename = null,
		/** Identifier for the uploaded LOA document. */
		public ?string $id = null,
		/** File size of the uploaded LOA document. */
		public ?int $sizeBytes = null,
		/** Whether the LOA has been verified by Cloudflare staff. */
		public ?bool $verified = null,
		/** Timestamp of the moment the LOA was marked as validated. */
		public ?\DateTimeImmutable $verifiedAt = null,
	) {
	}
}
