<?php

/**
 * This file is auto-generated. Do not edit manually.
 * Generated: 2026-06-09 21:41:47 UTC
 * Spec: https://raw.githubusercontent.com/cloudflare/api-schemas/main/openapi.json
 */

declare(strict_types=1);

namespace FoundryCo\Cloudflare\Responses;

readonly class WHOISRecordRecord
{
	public function __construct(
		public bool $dnssec,
		public string $domain,
		public string $extension,
		public bool $found,
		public array $nameservers,
		public string $punycode,
		public string $registrant,
		public string $registrar,
		public ?string $administrativeCity = null,
		public ?string $administrativeCountry = null,
		public ?string $administrativeEmail = null,
		public ?string $administrativeFax = null,
		public ?string $administrativeFaxExt = null,
		public ?string $administrativeId = null,
		public ?string $administrativeName = null,
		public ?string $administrativeOrg = null,
		public ?string $administrativePhone = null,
		public ?string $administrativePhoneExt = null,
		public ?string $administrativePostalCode = null,
		public ?string $administrativeProvince = null,
		public ?string $administrativeReferralUrl = null,
		public ?string $administrativeStreet = null,
		public ?string $billingCity = null,
		public ?string $billingCountry = null,
		public ?string $billingEmail = null,
		public ?string $billingFax = null,
		public ?string $billingFaxExt = null,
		public ?string $billingId = null,
		public ?string $billingName = null,
		public ?string $billingOrg = null,
		public ?string $billingPhone = null,
		public ?string $billingPhoneExt = null,
		public ?string $billingPostalCode = null,
		public ?string $billingProvince = null,
		public ?string $billingReferralUrl = null,
		public ?string $billingStreet = null,
		public ?\DateTimeImmutable $createdDate = null,
		public ?string $createdDateRaw = null,
		public ?\DateTimeImmutable $expirationDate = null,
		public ?string $expirationDateRaw = null,
		public ?string $id = null,
		public ?string $registrantCity = null,
		public ?string $registrantCountry = null,
		public ?string $registrantEmail = null,
		public ?string $registrantFax = null,
		public ?string $registrantFaxExt = null,
		public ?string $registrantId = null,
		public ?string $registrantName = null,
		public ?string $registrantOrg = null,
		public ?string $registrantPhone = null,
		public ?string $registrantPhoneExt = null,
		public ?string $registrantPostalCode = null,
		public ?string $registrantProvince = null,
		public ?string $registrantReferralUrl = null,
		public ?string $registrantStreet = null,
		public ?string $registrarCity = null,
		public ?string $registrarCountry = null,
		public ?string $registrarEmail = null,
		public ?string $registrarFax = null,
		public ?string $registrarFaxExt = null,
		public ?string $registrarId = null,
		public ?string $registrarName = null,
		public ?string $registrarOrg = null,
		public ?string $registrarPhone = null,
		public ?string $registrarPhoneExt = null,
		public ?string $registrarPostalCode = null,
		public ?string $registrarProvince = null,
		public ?string $registrarReferralUrl = null,
		public ?string $registrarStreet = null,
		public ?array $status = null,
		public ?string $technicalCity = null,
		public ?string $technicalCountry = null,
		public ?string $technicalEmail = null,
		public ?string $technicalFax = null,
		public ?string $technicalFaxExt = null,
		public ?string $technicalId = null,
		public ?string $technicalName = null,
		public ?string $technicalOrg = null,
		public ?string $technicalPhone = null,
		public ?string $technicalPhoneExt = null,
		public ?string $technicalPostalCode = null,
		public ?string $technicalProvince = null,
		public ?string $technicalReferralUrl = null,
		public ?string $technicalStreet = null,
		public ?\DateTimeImmutable $updatedDate = null,
		public ?string $updatedDateRaw = null,
		public ?string $whoisServer = null,
	) {
	}
}
